Fix update dict key error
BlackSamorez/tensor_parallel pull request #108
Opened 2023-07-25 02:27 UTC by tonywang16

Fix #107 KeyError when add new attr_rules.

Before: 
```python
config.attr_rules: {re.compile('.*self_attn$'): {'hidden_size': functools.partial(<function split_inner_dim at 0x7f38e434dfc0>, num_heads=64, world_size=2), 'num_heads': <function get_llama_config.<locals>.<lambda> at 0x7f39a9662200>}}
``` 
After
```python
config.attr_rules: {re.compile('.*self_attn$'): {'hidden_size': functools.partial(<function split_inner_dim at 0x7f38e434dfc0>, num_heads=64, world_size=2), 'num_heads': <function get_llama_config.<locals>.<lambda> at 0x7f39a9662200>, 'num_key_value_heads': functools.partial(<function split_num_heads at 0x7f38e434df30>, world_size=2)}}
```

2023-07-25 07:32 UTC, BlackSamorez commented
What exactly did you fix here? Regular expressions are supposed to be uncompiled in config to be compiled later during model creation.

2023-07-26 02:38 UTC, tonywang16 commented
> What exactly did you fix here? Regular expressions are supposed to be uncompiled in config to be compiled later during model creation.
hi
It failed to add new key/pair value for '.*self_attn$'
`File "/root/anaconda3/envs/tt/lib/python3.10/site-packages/tensor_parallel/slicing_configs.py", line 403, in get_llama_config config.attr_rules[r".*self_attn$"]["num_key_value_heads"] = partial(split_num_heads, world_size=world_size) KeyError: '.*self_attn$'` is having issue finding the key r".*self_attn$

use [re.compile(r".*self_attn$")] as the key it finds the dict and adding the new attribute to the config.

2023-07-26 14:42 UTC, BlackSamorez commented
Also could you, please, modify [pretrained_model.py](./src/tensor_parallel/pretrained_model.py) like this:
```python
def find_predefined_tensor_parallel_config(
    model_config: PretrainedConfig, device_ids: Optional[Sequence[torch.device]]
) -> Optional[Config]:
    device_ids = check_device_ids(device_ids)

    try:
        config_getter = PREDEFINED_CONFIGS[model_config.model_type]
    except KeyError:
        logger.warning(
            "Using automatic config: tensor parallel config not provided and no custom config registered for the model"
        )
        return None

    return config_getter(model_config, device_ids)
```
This would fix such false positives in tests.

2023-07-26 14:42 UTC, BlackSamorez requested changes

2023-07-26 15:20 UTC, merged